/**
 * Branded primitive types for domain identifiers.
 *
 * Branding prevents accidental mix-ups between IDs at compile time
 * (e.g., passing a PatientId where a DoseId is expected).
 * All are `string` at runtime — the brand exists only in the type system.
 *
 * @satisfies REQ-006 REQ-007 REQ-008
 */

export type DoseId    = string & { readonly __brand: 'DoseId' };
export type PatientId = string & { readonly __brand: 'PatientId' };
export type ActorId   = string & { readonly __brand: 'ActorId' };

/** UUID v4 string. Generated by the repository adapter, never by business logic. */
export type EventId   = string & { readonly __brand: 'EventId' };

/** All valid status values for an alert. Used by the PostgreSQL CHECK constraint. */
export type AlertStatus =
  | 'INACTIVE'
  | 'ALERT_ACTIVE'
  | 'ALERT_ESCALATED'
  | 'ACKNOWLEDGED';
